# Generated by Django 3.2.13 on 2022-05-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('mailing_address', models.TextField(max_length=256, null=True)),
                ('date_placed', models.DateField(auto_now_add=True)),
                ('date_paid', models.DateField()),
                ('date_purchased', models.DateField()),
                ('date_arrived', models.DateField()),
                ('order_tag', models.CharField(default='[CeQRXbjJ1jAoU3pRDpx1mQSu9BOzViFh1nT_veqrfdM]', max_length=32)),
                ('xmr_per_usd_rate', models.FloatField()),
                ('processing_fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('supplier_url', models.URLField(max_length=256)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='XMRExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.storeitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
