# Generated by Django 3.2.13 on 2022-05-04 18:30

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('key', models.BinaryField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('mailing_address', models.BinaryField(max_length=300, null=True)),
                ('state', models.IntegerField(default=orders.models.Order.State['CREATED'])),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField()),
                ('date_purchased', models.DateTimeField()),
                ('date_arrived', models.DateTimeField()),
                ('xmr_address', models.CharField(max_length=105, null=True, unique=True)),
                ('xmr_per_usd_rate', models.DecimalField(decimal_places=10, max_digits=10)),
                ('processing_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encrypt_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.encryptkeys')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='XMRExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=128, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('visible', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('supplier_url', models.URLField(max_length=256)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.storeitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
